### ISSUE TITLE
Remove poweriso command-line tool

### ISSUE THREAD

**Issue by hadess** [flathub/com.poweriso.PowerISO#1]
It's a 32-bit app...

```
$ strace -vvv /app/bin/poweriso
<snip>
[ Process PID=14 runs in 32 bit mode. ]
strace: WARNING: Proper structure decoding for this personality is not supported, please consider building strace with mpers support enabled.
uname( <unfinished ...>)                = ?
+++ killed by SIGSYS (core dumped) +++
Bad system call (core dumped)
```

**Comment by tinywrkb** [comment]
Why not keep it? it's nice to have the command-line tool already in a container, it doesn't seem to need 32bit libc, just add `--allow=multiarch`.

**Comment by hadess** [comment]
> Why not keep it? it's nice to have the command-line tool already in a container, it doesn't seem to need 32bit libc, just add `--allow=multiarch`.

Good call, thanks.
